Use setuptools_scm to determine the version (#151)
This fixes an issue where cffi was required to build a wheel:

    $ python setup.py bdist_wheel
    Traceback (most recent call last):
      File "setup.py", line 6, in <module>
        exec(open("mip/constants.py").read(), version_dict)
      File "<string>", line 4, in <module>
    ModuleNotFoundError: No module named 'cffi'

It should also streamline the process of making a release a tiny bit.