Fix logical errors in Gurobi check (#149)
* Fix logical errors in Gurobi check

* Fix circular import (`ImportError: cannot import name 'Model'
  from partially initialized module 'mip' (most likely due to a
  circular import)`)
* Fix logic for setting `mip.gurobi.found` flag

* Provide useful exception if gurobi is specifically requested but cannot be found